### ISSUE TITLE
error 'control.tar.gz' not found in archive

### ISSUE THREAD

**Issue by jessereynolds** [dnbert/prm#35]
prm throws an exception for me when I try and update a repository after copying in a package file. Not sure if I'm doing anything wrong here...

``` bash
# initialize the deb repo
$ prm --type deb --path pool --component dev,staging --release precise --arch amd64 --gpg

# copy in the latest flapjack deb
$ cp -p ~/src/flpjck/omnibus-flapjack/pkg/flapjack_0.8.2+20140119234113-1.ubuntu.12.04_amd64.deb pool/dists/precise/dev/binary-amd64/

# run npm
$ prm --type deb --path pool --component dev,staging --release precise --arch amd64
Building Path: pool/dists/precise/dev/binary-amd64/
Generating Packages: precise : dev : binary-amd64
ar: control.tar.gz: not found in archive
/Users/jesse/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/prm-0.2.9/lib/prm/repo.rb:133:in `read': No such file or directory - tmp/flapjack_0.8.2+20140119234113-1.ubuntu.12.04_amd64.deb/control (Errno::ENOENT)
    from /Users/jesse/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/prm-0.2.9/lib/prm/repo.rb:133:in `block (2 levels) in generate_packages_gz'
    from /Users/jesse/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/prm-0.2.9/lib/prm/repo.rb:131:in `synchronize'
    from /Users/jesse/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/prm-0.2.9/lib/prm/repo.rb:131:in `block in generate_packages_gz'
    from /Users/jesse/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/peach-0.5.1/lib/peach.rb:22:in `block (2 levels) in peach'
    from /Users/jesse/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/peach-0.5.1/lib/peach.rb:22:in `each'
    from /Users/jesse/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/peach-0.5.1/lib/peach.rb:22:in `block in peach'
    from /Users/jesse/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/peach-0.5.1/lib/peach.rb:13:in `block (2 levels) in _peach_run'
```

**Comment by justincletus** [comment]
> I think the problem here is not `ar` but your deb.
> 
> Your output follows:
> 
> ```
> $ ar t pool/dists/precise/dev/binary-amd64/flapjack_0.8.2+20140119234113-1.ubuntu.12.04_amd64.deb
> debian-binary/
> control.tar.gz/
> data.tar.gz/
> ```
> 
> The trailing / makes me think that your ar includes files literally named "control.tar.gz/" or perhaps a directory simply named that. EIther way, it's not correct for a .deb file.
> 
> What created this .deb?

I have same issue after created using fpm. How to fix this?
debian-binary/
control.tar.gz/
data.tar.gz/
bundle exec fpm \
    --name "${buildPackage}" \
    --input-type dir \
    --output-type deb \
    --version "1.0.0" \
    --chdir "${buildPackage}" \
    --license 'Proprietary' \
    --vendor 'Self' \
    --maintainer 'justinbeckh@gmail.com' \
    --architecture 'amd64' \
    --description 'Debian App'
}

**Comment by kcrouch** [comment]
For anyone finding this years later, the default darwin-supplied `ar` binary has issues with some subset of debian files.

using the default darwin-supplied `ar`:

```
$ ar t ../filebeat-8.11.1-amd64.deb 
debian-binary/
control.tar.gz/
data.tar.gz/
_gpgelastic
```

Only the `_gpgelastic` member can be extracted

```
$ ar x ../filebeat-8.11.1-amd64.deb 
ar: debian-binary/: No such file or directory
ar: control.tar.gz/: No such file or directory
ar: data.tar.gz/: No such file or directory
$ ls
_gpgelastic
$
```

using `ar` from brew's binutils v2.41:

```
$ ar t ../filebeat-8.11.1-amd64.deb 
debian-binary
control.tar.gz
data.tar.gz
_gpgelastic
$ ar x ../filebeat-8.11.1-amd64.deb 
$ ls
_gpgelastic	control.tar.gz	data.tar.gz	debian-binary
$ 
```

All members of the archive are extracted correctly.

EDIT: The debian package I'm testing on is the latest official version of Filebeat which installs as expected on a debian machine.  The darwin `ar` utility definitely has issues with it.
