### ISSUE TITLE
Command line does not supply --version

### ISSUE THREAD

**Issue by thedrow** [dnbert/prm#43]
It should be easy to fix no?

**Comment by jgoldschrafe** [comment]
Related, this project hasn't seen a release in about a year, despite a couple of important bug fixes and feature enhancements (*cough*). How about a 0.2.10? :)

**Comment by dnbert** [comment]
@jgoldschrafe Definitely at that is totally my fault, life got in the way a bit. Just released 0.2.10 and will probably release 0.2.11 tonight as well to support some of these long standing bugs.
