### ISSUE TITLE
Document usage with S3 buckets

### ISSUE THREAD

**Issue by thedrow** [dnbert/prm#44]
I'm assuming it's the same as DreamObjects but I can't be sure.

**Comment by thedrow** [comment]
Any updates?

**Comment by thedrow** [comment]
@dnbert Sorry to nag you but I'd really like to use this project.
I just don't know how to do so with S3.

**Comment by dnbert** [comment]
@thedrow Sorry for being so long to add support for this. I've finally done it now with the -u flag
